Controllers/ReportController.cs
using GleamTech.DocumentUltimate.AspNet.UI;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using WebTools.Extensions;
using WebTools.Models;
using WebTools.Models.Entities;
using WebTools.Services;
using WebTools.Services.Interface;

namespace WebTools.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        #region Connnection Database

        private readonly IConfiguration _configuration;
        private readonly IReportListServices _reportListServices;
        private readonly IReportVersionServices _reportVersionServices;
        private readonly IReportSoftServices _reportSoftServices;
        private readonly IReportDetailServices _reportDetailServices;
        private readonly IReportURDServices _reportURDServices;
        private readonly IDepts _depts;
        private readonly ISoftwareServices _softwareServices;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IGoogleDriveAPI _googleDriveAPI;
        private readonly IUploadFileServices _uploadFileServices;
        private readonly IUnitOfWork _services;

        public ReportController(
            IConfiguration configuration,
            IReportListServices reportListServices,
            IReportVersionServices reportVersionServices,
            IReportSoftServices reportSoftServices,
            IReportDetailServices reportDetailServices,
            IReportURDServices reportURDServices,
            IDepts depts,
            ISoftwareServices softwareServices,
            IWebHostEnvironment webHostEnvironment,
            IUploadFileServices uploadFileServices,
            IGoogleDriveAPI googleDriveAPI,
            IUnitOfWork services
            )
        {
            _configuration = configuration;
            _reportListServices = reportListServices;
            _reportVersionServices = reportVersionServices;
            _reportSoftServices = reportSoftServices;
            _reportDetailServices = reportDetailServices;
            _reportURDServices = reportURDServices;
            _depts = depts;
            _softwareServices = softwareServices;
            _webHostEnvironment = webHostEnvironment;
            _uploadFileServices = uploadFileServices;
            _googleDriveAPI = googleDriveAPI;
            _services = services;
        }
        #endregion

        #region Index Page

        public async Task<IActionResult> Index()
        {
            ReportListViewModel model = new ReportListViewModel();
            model.URDs = new SelectList((await _reportURDServices.GetAll_URDAsync()).OrderBy(i => i.Des), "ID", "Des");
            model.Cabinnet = new SelectList((await _services.DanhMuc.Get_LoaiCabinet()), "ID", "DES");
            model.ReportLists = await _reportListServices.GetReportListAsync();
            return View(model);
        }

        public async Task<JsonResult> SearchReportList(string searchString, string searchTrangThaiSD, string searchTrangThaiPM, string searchDate, string searchURD, string loai, string searcCabinnet)
        {
            if (!String.IsNullOrEmpty(loai) && loai == "1")
            {
                var data = await _reportListServices.SearchReportListAsync(searchURD, searchString, searchDate, searchTrangThaiSD, searchTrangThaiPM, searcCabinnet);

                return Json(new { data });
            }
            else if (!String.IsNullOrEmpty(loai) && loai == "2")
            {
                List<GoogleDriveFile> Table = new List<GoogleDriveFile>();
                if (!String.IsNullOrEmpty(searchString)) { Table = await _googleDriveAPI.SearchDriveFiles(searchString); }
                else { Table = null; }
                var data = await _reportListServices.SearchReportNameAsync(searchURD, Table);
                if (!String.IsNullOrEmpty(searchDate))
                {
                    data = data.Where(s => s.NgayBanHanh != null && s.NgayBanHanh.Contains(searchDate.ToString())).ToList();
                }
                if (!String.IsNullOrEmpty(searchTrangThaiSD))
                {
                    switch (searchTrangThaiSD)
                    {
                        case "0":
                            searchTrangThaiSD = "";
                            break;
                        case "1":
                            searchTrangThaiSD = "Đang sử dụng";
                            break;
                        case "2":
                            searchTrangThaiSD = "Chưa ban hành";
                            break;
                        case "3":
                            searchTrangThaiSD = "Đã hủy";
                            break;
                    }
                    data = data.Where(s => s.TrangThai.ToLower().Contains(searchTrangThaiSD.ToLower())).ToList();
                }
                if (!String.IsNullOrEmpty(searchTrangThaiPM))
                {
                    switch (searchTrangThaiPM)
                    {
                        case "0":
                            searchTrangThaiPM = "";
                            break;
                        case "1":
                            searchTrangThaiPM = "Đã hoàn thành";
                            break;
                        case "2":
                            searchTrangThaiPM = "Chưa hoàn thành";
                            break;
                        case "3":
                            searchTrangThaiPM = "Chưa có";
                            break;
                    }
                    data = data.Where(s => s.TrangThaiPM.ToLower().Contains(searchTrangThaiPM.ToLower())).ToList();
                }
                return Json(new { data });
            }
            else
            {
                var data = await _reportListServices.SearchReportListAsync();
                return Json(new { data });
            }
        }
        #endregion

        #region Khử dấu cho string        
        public static string convertToUnSign(string s)
        {
            Regex regex = new Regex("\\p{IsCombiningDiacriticalMarks}+");
            string temp = s.Normalize(NormalizationForm.FormD);
            return regex.Replace(temp, String.Empty).Replace('\u0111', 'd').Replace('\u0110', 'D');
        }
        #endregion

        #region Biểu mẫu
        [HttpGet]
        public async Task<IActionResult> AddReport()
        {
            ReportListViewModel model = new ReportListViewModel();
            model.Depts = new SelectList((await _depts.GetAll_DeptsAsync()).OrderBy(i => i.KhoaP), "STT", "KhoaP");
            return PartialView("_AddReportPartial", model);
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        public async Task<JsonResult> AddReport_Json(ReportList reportList)
        {
            string message = String.Empty;
            string title = String.Empty;
            string result = String.Empty;
            try
            {
                if (!String.IsNullOrEmpty(reportList.MaBM))
                {
                    var data = await _reportListServices.GetReportListAsync();
                    bool has = data.Any(r => r.MaBM != null && StaticHelper.RemoveSpecialCharacters(r.MaBM).ToUpper() == StaticHelper.RemoveSpecialCharacters(reportList.MaBM).ToUpper());
                    if (has)
                    {
                        message = $"Mã biểu mẫu: <b>{reportList.MaBM}</b> đã tồn tại trên hệ thống. Xin vui lòng kiểm tra lại.";
                        title = "Thông báo!";
                        result = "info";
                        return Json(new { Result = result, Title = title, Message = message });
                    }
                }

                reportList.CreatedUser = HttpContext.User.Claims.First(c => c.Type == ClaimTypes.GivenName).Value ?? HttpContext.User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier).Value;
                reportList.FileLink = await _uploadFileServices.UploadFileAsync(reportList.fileUpload);
                if (reportList.fileUpload != null && String.IsNullOrEmpty(reportList.FileLink))
                {
                    message = $"File <b>{reportList.fileUpload.FileName}</b> tải lên không thành công. Vui lòng kiểm tra lại file.";
                    title = "Lỗi!";
                    result = "error";
                }
                else
                {
                    result = await _reportListServices.InsertReportListAsync(reportList);
                    if (result == "OK")
                    {
                        message = $"Đã thêm biểu mẫu <b>{reportList.TenBM}</b> thành công.";
                        title = "Thành công!";
                        result = "success";
                    }
                    else
                    {
                        message = result;
                        title = "Lỗi!";
                        result = "error";
                    }
                }

            }
            catch (Exception ex)
            {
                message = ex.Message;
                title = "Lỗi!";
                result = "error";
            }
            return Json(new { Result = result, Title = title, Message = message });
        }

        [HttpGet]
        public async Task<IActionResult> EditReport(string id)
        {
            ReportListViewModel model = new ReportListViewModel();
            model.ReportList = await _reportListServices.GetReportByIDAsync(id);
            model.Depts = new SelectList((await _depts.GetAll_DeptsAsync()).OrderBy(i => i.KhoaP), "STT", "KhoaP");
            return PartialView("_EditReportPartial", model);
        }

Controllers/ReportsController.cs
using GleamTech.DocumentUltimate.AspNet.UI;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Stimulsoft.Report;
using Stimulsoft.Report.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using WebTools.Models.Entities;
using WebTools.Services;

namespace WebTools.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IUnitOfWork _services;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ReportsController(IWebHostEnvironment webHostEnvironment, IUnitOfWork services)
        {
            _services = services;
            _webHostEnvironment = webHostEnvironment;
        }

        public class FileReport
        {
            public string filePath { get; set; }
        }
        public class TestModel
        {
            public string ID { get; set; }
            public string MaBM { get; set; }
            public string TenBM { get; set; }
            public string URD { get; set; }
            public string KhoaPhong { get; set; }
        }       

        public async Task<IActionResult> GetReport(string reportName, string jsonContent)
        {
            ViewBag.FilePath = JsonConvert.DeserializeObject<FileReport>(await _services.ReportsAPI.GetReport(reportName, jsonContent)).filePath;
            return View();
        }

        public IActionResult Overview(string filePath)
        {
            var documentViewer = new DocumentViewer
            {
                Width = 1100,
                Height = 600,
                Resizable = true,
                Document = filePath
            };

            return View(documentViewer);
        }       

        
    }
}

Controllers/ThongKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebTools.Models.Entities;
using WebTools.Models.ViewModel;
using WebTools.Services;

namespace WebTools.Controllers
{
    [Authorize]
    public class ThongKeController : Controller
    {
        #region Services
        private readonly IUnitOfWork _services;
        public ThongKeController(IUnitOfWork services)
        {
            _services = services;
        } 
        #endregion

        #region Thống kê chi tiết theo phạm vi văn bản
        public IActionResult ThongKePhamViVanBan()
        {
            ThongKeVanBanVM model = new ThongKeVanBanVM();
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetTable_ThongKeTheoPhamVi(SearchThongKe search)
        {
            return Json(new { data = await _services.ThongKe.GetData_ThongKePhamVi(search) });
        }
        #endregion

        #region Thống kê số lượng user đã đọc và hiểu nội dung văn bản
        public IActionResult ThongKeSoLuongXacNhan()
        {
            ThongKeVanBanVM model = new ThongKeVanBanVM();
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> GetTable_ThongKeSoLuongXacNhan(SearchThongKe search)
        {
            return Json(new { data = await _services.ThongKe.GetData_BaoCaoDocHieu(search) });
        }

        public IActionResult ThongKeDocHieuChiTiet(string idvb)
        {
            ViewBag.IDVB = idvb;
            return PartialView("_ThongKeDocHieu_ChiTiet");
        }

        [HttpGet]
        public async Task<JsonResult> Get_ThongKeDocHieuChiTiet(string idvb)
        {
            return Json(new { data = await _services.ThongKe.GetData_BaoCaoDocHieuChiTiet(idvb) });
        }
        #endregion

        #region Báo cáo thống kê tổng hợp
        public IActionResult ThongKeTongHop()
        {
            return View();
        }

        public async Task<JsonResult> GetTable_ThongKeTongHop(SearchThongKe search)
        {
            return Json(new { data = await _services.ThongKe.GetData_ThongKeTongHop(search) });
        }
        #endregion

        #region Biểu đồ
        public async Task<IActionResult> BieuDoThongKe(string loaibc = null)
        {
            ThongKeVM model = new ThongKeVM();
            var data = (await _services.ThongKe.Get_DataBieuDo()).GroupBy(i => new { i.LoaiBC, i.TenBC }).ToList();
            List<ThongKe_BieuDo> list = new List<ThongKe_BieuDo>();
            foreach (var key in data)
            {
                ThongKe_BieuDo item = new ThongKe_BieuDo() { LoaiBC = key.Key.LoaiBC, TenBC = key.Key.TenBC};
                list.Add(item);
            }
            model.ListBieuDo = list;
            model.countBC = data.Count;
            return View(model);
        }

        [HttpGet]
        public async Task<JsonResult> Get_DashboardData(string loaibc = null)
        {
            var data = (await _services.ThongKe.Get_DataBieuDo()).Where(i => i.LoaiBC.Contains(loaibc));
            return Json(new { data });
        }
        #endregion
    }
}

Views/Shared/NotFound.cshtml
@{
    ViewData["Title"] = ViewBag.ErrorMessage;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        margin: 0;
        padding: 0;
    }

    p {
        margin: 0;
    }

    .layout-navbar-fixed .wrapper .content-wrapper {
        margin-top: 50px;
    }

    .error-page > .error-content {
        margin-left: 50px;
    }
</style>
<div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
        <div class="error-page">
            <br />
            <div class="col">
                <div class="error-content text-center" style="font-size:25px; font-weight:bold">
                    <h2><i class="fas fa-exclamation-triangle text-warning"></i> @ViewBag.ErrorMessage</h2>

                    <p>
                        @ViewBag.Msg
                        <br />
                        <a href="@Url.Action("Index","Home")">Bấm vào đây để trở về trang chủ</a>
                    </p>
                </div>
            </div>
            <div class="col">
                <img src="@ViewBag.ErrorImage" alt="error-@ViewBag.ErrorMessage" />
            </div>

            <!-- /.error-content -->
        </div>
        <!-- /.error-page -->
    </section>
    <!-- /.content -->
</div>

Views/Shared/_Datatable_Scripts.cshtml
<!-- DataTables  & Plugins -->
<script src="~/lib/datatables/jquery.dataTables.min.js"></script>
<script src="~/lib/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/lib/datatables-fixedheader/js/dataTables.fixedHeader.min.js"></script>
<script src="~/lib/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/lib/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

<script src="~/lib/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/lib/datatables-buttons/js/buttons.flash.min.js"></script>
<script src="~/lib/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/lib/datatables-buttons/js/jszip.min.js"></script>

<script src="~/lib/datatables-select/js/dataTables.select.min.js"></script>
<script src="~/lib/datatables-checkboxes/js/dataTables.checkboxes.min.js"></script>
<script src="~/lib/datatables-rowgroup/js/dataTables.rowGroup.min.js"></script>

Views/Shared/_Datatable_Styles.cshtml
<link rel="stylesheet" href="~/lib/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/lib/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/lib/datatables-fixedheader/css/fixedHeader.bootstrap4.min.css">
<link rel="stylesheet" href="~/lib/datatables-select/css/select.bootstrap4.min.css">
<link rel="stylesheet" href="~/lib/datatables-checkboxes/css/dataTables.checkboxes.css">

Views/Shared/_DevExpressReportingResources.cshtml
<link rel="stylesheet" href="~/css/thirdparty.bundle.css" />
<link rel="stylesheet" href="~/css/viewer.part.bundle.css" />
<script src="~/js/thirdparty.bundle.js"></script>
<script src="~/js/viewer.part.bundle.js"></script>

Views/Shared/_DevExpressRichTextEditorResources.cshtml
<link href="~/node_modules/devextreme/dist/css/dx.light.css" rel="stylesheet" />
<link href="~/node_modules/devexpress-richedit/dist/dx.richedit.css" rel="stylesheet" />
@* For v2020.1 and earlier, add the following code: *@
@*<link href="~/node_modules/devextreme/dist/css/dx.common.css" rel="stylesheet" />*@

<script src="~/node_modules/jszip/dist/jszip.min.js"></script>
<script src="~/node_modules/devextreme/dist/js/dx.all.js"></script>

@* If you localize the control, you should register localization resources before control script registration.*@
@*<script src="~/node_modules/devexpress-richedit/localization/dx-rich.de.js"></script>*@

@* If you export a document to PDF on the client side (the exportToPdf method) or enable client PDF printing mode,
    you should register the pdfkit library before control script registration.*@
@*<script src="~/node_modules/devexpress-richedit/dist/pdfkit.js"></script>*@

<script src="~/node_modules/devexpress-richedit/dist/dx.richedit.js"></script>

Views/Shared/_EasyUI_Scripts.cshtml
<!-- EasyUI -->
<script type="text/javascript" src="~/lib/easyui/js/jquery.easyui.min.js"></script>
<script type="text/javascript" src="~/lib/easyui/js/locale/easyui-lang-en.js"></script>
<!-- Plugins -->
<script type="text/javascript" src="~/lib/easyui/js/plugins/jquery.datagrid.js"></script>
<script type="text/javascript" src="~/lib/easyui/js/plugins/jquery.treegrid.js"></script>
<script type="text/javascript" src="~/lib/easyui/js/plugins/jquery.tree.js"></script>

Views/Shared/_EasyUI_Styles.cshtml
<!-- EasyUI -->
<link rel="stylesheet" type="text/css" href="~/lib/easyui/css/metro/easyui.css">
<link rel="stylesheet" type="text/css" href="~/lib/easyui/css/icon.css">

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tâm Anh Hospital</title>
    <!-- Plugins -->
    @await Html.PartialAsync("_Plugins_Styles")
    <!-- DataTables -->
    @await Html.PartialAsync("_Datatable_Styles")
    <!-- EasyUI -->
    @await Html.PartialAsync("_EasyUI_Styles")
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/loading.css">
    <link rel="stylesheet" href="~/lib/admin-lte/css/adminlte.min.css">
    <link rel="stylesheet" href="~/css/site_default.css">
    <style>
        .narh-50 {
            height: 50px;
        }
    </style>
</head>
<body class="control-sidebar-slide-open layout-navbar-fixed sidebar-collapse">
    <div class="wrapper">
        @if (User.Identity.IsAuthenticated)
        {
            <header>
                <nav class="main-header navbar navbar-expand navbar-dark border-bottom-0 narh-50">
                    <ul class="navbar-nav narh-50">
                        <li class="nav-item narh-50">
                            <a class="navbar-brand" role="button" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/images/logo_compact_white_200x200.png" width="38" height="38" style="vertical-align: middle;" alt="">
                            </a>
                        </li>
                        <li class="nav-item dropdown dropdown-hover narh-50">
                            <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Văn bản</a>
                            <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                                <li><a asp-area="" asp-controller="VanBan" asp-action="DanhMuc_VanBan" class="dropdown-item">Bảng tin văn bản</a></li>
                                <li><a asp-area="" asp-controller="VanBan" asp-action="DanhSach_VanBanChiTiet" class="dropdown-item">Danh sách chi tiết văn bản</a></li>
                                @if (User.IsInRole("Admin"))
                                {
                                    <li><a asp-area="" asp-controller="Report" asp-action="Index" class="dropdown-item">Danh sách tổng hợp</a></li>
                                }
                                @if (User.IsInRole("Admin") || User.IsInRole("Document"))
                                {
                                    <li class="nav-item dropdown-submenu dropdown-hover">
                                        <a class="dropdown-item">Báo cáo Thống kê</a>
                                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                                            <li><a asp-area="" asp-controller="ThongKe" asp-action="ThongKePhamViVanBan" class="dropdown-item">Thống kê theo phạm vi văn bản</a></li>
                                            <li><a asp-area="" asp-controller="ThongKe" asp-action="ThongKeSoLuongXacNhan" class="dropdown-item">Thống kê đã đọc và hiểu văn bản</a></li>
                                            <li><a asp-area="" asp-controller="ThongKe" asp-action="ThongKeTongHop" class="dropdown-item">Thống kê tổng hợp</a></li>
                                            <li><a asp-area="" asp-controller="ThongKe" asp-action="BieuDoThongKe" class="dropdown-item">Biểu đồ tròn</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item dropdown-submenu dropdown-hover">
                                        <a class="dropdown-item">Danh mục</a>
                                        <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                                            <li><a asp-area="" asp-controller="DanhMuc" asp-action="Cabinet" class="dropdown-item">Danh mục Cabinet</a></li>
                                            <li><a asp-area="" asp-controller="DanhMuc" asp-action="LoaiVanBan" class="dropdown-item">Danh mục Loại văn bản</a></li>
                                            <li><a asp-area="" asp-controller="DanhMuc" asp-action="KhoaPhong" class="dropdown-item">Danh mục Khoa phòng</a></li>
                                        </ul>
                                    </li>
                                }
                            </ul>
                        </li>
                        <li class="nav-item d-none d-sm-inline-block narh-50">
                            <a class="nav-link narh-50" data-toggle="ajax-modal" data-target="#GopY" data-url="/GopY/Index">Góp ý</a>
                        </li>
                        @if (User.IsInRole("Admin") || User.IsInRole("Document"))
                        {
                            <li class="nav-item dropdown dropdown-hover narh-50">
                                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Phân quyền</a>
                                <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                                    @if (User.IsInRole("Admin") || User.IsInRole("Document"))
                                    {
                                        <li><a asp-area="" asp-controller="PhanQuyen" asp-action="QuyenLoaiVanBan" class="dropdown-item">Theo loại văn bản</a></li>
                                    }
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <li><a asp-area="" asp-controller="PhanQuyen" asp-action="QuyenHeThong" class="dropdown-item">Theo hệ thống</a></li>
                                    }
                                </ul>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown dropdown-hover narh-50">
                                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle">Test</a>
                                <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                                    <li><a asp-area="" asp-controller="Preview" asp-action="VanBanKy" class="dropdown-item">Chữ ký Demo</a></li>
                                    <li><a asp-area="" asp-controller="VanBan" asp-action="GoogleDocs" class="dropdown-item">Tạo File Google Docs</a></li>
                                    <li><a asp-area="" asp-controller="DocEditer" asp-action="Index" class="dropdown-item">Document Editer</a></li>
                                    <li><a asp-area="" asp-controller="Reports" asp-action="Index" class="dropdown-item">Report Test</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto narh-50">
                        <li class="nav-item narh-50">
                            <partial name="_LoginStatusPartial" />
                        </li>
                    </ul>
                </nav>
            </header>
            <div class="content-wrapper">
                <div id="ReportPopup"></div>
                @RenderBody()
            </div>
            <div class="modal-loading"><!-- Place at bottom of page --></div>
        }
        <!-- Plugins -->
        @await Html.PartialAsync("_Plugins_Scripts")
        <!-- DataTables -->
        @await Html.PartialAsync("_Datatable_Scripts")
        <!-- EasyUI -->
        @await Html.PartialAsync("_EasyUI_Scripts")
        <!-- AdminLTE App -->
        <script src="~/lib/admin-lte/js/adminlte.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script type="text/javascript">
            $('body').on('click', 'a[data-toggle="ajax-modal"]', function (event) {
                var url = $(this).data('url');
                $(this).callModal(url);
            });
        </script>
        @await RenderSectionAsync("Scripts", required: false)
    </div>
</body>
</html>

Views/Shared/_LoginStatusPartial.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


@if (User.Identity.IsAuthenticated)
{
    <a class="nav-link" href="/User/Logout">@User.Identity.Name (IP: @Context.Connection.RemoteIpAddress.MapToIPv4().ToString())</a>
}
else
{
    <a class="nav-link" href="/User/Login">Đăng nhập</a>
}